version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "5432:5432"
    networks:
      - hive-net

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    networks:
      - hive-net

  hive-server:
    image: bde2020/hive:2.3.2
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
    networks:
      - hive-net

  spark:
    image: bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - hive-net

  marketplace-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - spark
    volumes:
      - ./data:/app/data
    networks:
      - hive-net

networks:
  hive-net:
