version: "3.8"

services:
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    networks:
      - hive-net

  hive-server:
    image: bde2020/hive:2.3.2
    container_name: hive-server
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
    networks:
      - hive-net

  postgres:
    image: postgres:13
    container_name: hive-postgres
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "5432:5432"
    networks:
      - hive-net

  spark:
    image: bitnami/spark:3.5.1
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"   
      - "8080:8080"   
    networks:
      - hive-net

  marketplace-api:
    build: .
    container_name: marketplace-api
    ports:
      - "8000:8000"
    networks:
      - hive-net
    depends_on:
      - spark
    volumes:
      - ./data:/app/data

    

networks:
  hive-net:
